- hosts: localhost
  tasks:
    - name: Creates directory
      file:
        path: ~/tmp/{{RSX_MINECRAFT_USER}}
        state: directory
  tasks:
    - name: Creates directory
      file:
        path: ~/tmp/{{evn_var}}
        state: directory


